### ISSUE TITLE
how to calculate reverse ppl?

### ISSUE THREAD

**Issue by MokkeMeguru** [shentianxiao/text-autoencoders#3]
I read some papers related to the Language model. 
And I saw some models use KenLM for calculating normal/reverse perplexity
i.g. https://github.com/jakezhaojb/ARAE/blob/master/lang/train.py#L213-L237

But you use your model to calculate perplexity .
https://github.com/shentianxiao/text-autoencoders/blob/master/test.py#L96-L103

So I think we cannot calculate reverse perplexity only with this repository.
Can you give me some instructions to calculate reverse perplexity?

**Comment by shentianxiao** [comment]
Yes, you can use KenLM. I used pytorch word_language_model to compute forward/reverse PPL: https://github.com/pytorch/examples/tree/master/word_language_model

**Comment by M3skar** [comment]
@shentianxiao calculating reverse ppl using the mentioned word_language_model on yelp dataset,  i couldn't reproduce your results, can you give your configuration (hp values) for the yelp dataset ?
